# this is a example for action taking when version.py in main branch changed only.
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'version.py'

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          main: main
          exe_name: 'ps4debugportal'
          #icon: 'logo.png'
          artifact: true
          release: false
          token: ${{ secrets.TOKEN }}
          bodyfile: 'readme.MD'
