on: 
  push:
    branches:
      - 'main'

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            pyinstaller-args: >
              --onefile --clean --name ps4debugportal
              --add-data "templates;templates"
              --add-data "static;static"
              main.py
            artifact: ps4debugportal.exe
          - os: ubuntu-latest
            pyinstaller-args: >
              --onefile --clean --name ps4debugportal
              --add-data "templates:templates"
              --add-data "static:static"
              main.py
            artifact: ps4debugportal

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller (bundle templates/static)
        run: |
          pyinstaller ${{ matrix.pyinstaller-args }}

      - name: Upload executable to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/${{ matrix.artifact }}
